Try to fix Appveyor build.
Error was:

https://ci.appveyor.com/project/ppelleti/normalization-insensitive/builds/38208855

------------------------------------------
Install package dependencies
------------------------------------------
stack --no-terminal build --test --only-dependencies --ghc-options=-O0
Error: While constructing the build plan, the following exceptions were
encountered:
In the dependencies for text-1.2.4.1:
    binary must match >=0.5 && <0.9, but this GHC boot package has been pruned
           (issue #4510); you need to add the package explicitly to extra-deps
           (latest matching version is 0.8.8.0)
needed due to normalization-insensitive-2.0.2 -> text-1.2.4.1
Some different approaches to resolving this:
  * Recommended action: try adding the following to your extra-deps
    in C:\pkg\.sanity-test\normalization-insensitive-2.0.2\stack.yaml:
- binary-0.8.8.0@sha256:e9387a7ef2b34c6a23b09664c306e37cc01ae2cb4e4511a1c96ffb14008c24b0,6262
Plan construction failed.
Error: Command [stack --no-terminal build --test --only-dependencies --ghc-options=-O0] failed. Exiting.